spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/studify
    driver-class-name: org.mariadb.jdbc.Driver
    username: studify
    password: "studify123!"   #  지정한 비번
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace


springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui/index.html
