spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/studify
    driver-class-name: org.mariadb.jdbc.Driver
    username: studify
    password: "studify123!"
  jpa:
    hibernate:
      ddl-auto: update        # 처음엔 update로 테이블 자동 생성 확인
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        highlight_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
