spring:
    application:
        name: studify-be

    datasource:
        driver-class-name: ${DRIVER}
        url: ${URL}
        username: ${USER}
        password: ${PASSWD}
        
    jpa:
        hibernate: 
            ddl-auto: create
        show-sql: true     
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true

server:
    port: 8088